SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `ecg_analizer` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;

USE `ecg_analizer`;

CREATE  TABLE IF NOT EXISTS `ecg_analizer`.`etalons` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(128) NOT NULL ,
  PRIMARY KEY (`id`) ,
  INDEX `NameIndex` (`name` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE  TABLE IF NOT EXISTS `ecg_analizer`.`data` (
  `etalons_id` INT(11) NOT NULL ,
  `x` DOUBLE NOT NULL ,
  `y` FLOAT(11) NOT NULL ,
  INDEX `fk_data_etalons_idx` (`etalons_id` ASC) ,
  CONSTRAINT `fk_data_etalons`
    FOREIGN KEY (`etalons_id` )
    REFERENCES `ecg_analizer`.`etalons` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
